### ISSUE TITLE
[Crash] Mousing over a painting in my inventory from a previous session

### ISSUE THREAD

**Issue by faeldray** [GeheimagentNr1/SelectablePainting#1]
**Versions**
Minecraft Version: 1.16.5
Minecraft Forge Version: 36.1.61
Mod Version: 2.0.0

**Log files**
Crash report: https://gist.github.com/faeldray/17ef4728f6cc8f2efe59b26e6a48011c

**Describe the bug**
After loading a single player game where I had a selectable painting in my inventory, whenever I moused over the painting, the game would crash. The painting had been "configured" (AKA I had selected a particular painting during my previous session). The selected painting was a modded one if that matters.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start a new SP game and get a selectable painting.
2. Choose a painting.
3. Exit and reload the game.
4. Mouseover the painting.
5. Client crashes.

**Expected behaviour**
No crashes when mousing over the painting.

**Comment by GeheimagentNr1** [comment]
<table><tbody><tr><th>Status:</th><td>Fixed</td></tr><tr><th>Issue type:</th><td>Critical Bug</td></tr><tr><th>Fix type:</th><td>Bugfix</td></tr><tr><th>Fix version:</th><td>2.0.1</td></tr><tr><th>Fix release date:</th><td>05.08.2021</td></tr></tbody></table>

**Issue confirmed for:**

*   Minecraft version: 1.16.5  
    Forge: 36.2.2  
    Mod version:  2.0.0  
    Macaw's Paintings: 1.0.2  
    Infernal Expansion: 1.3

**TODOs:**

*   [x] Testing via Minecraft 1.16.5 and Forge 36.2.0 with mod version 2.0.0
*   [x] Testing with Minecraft 1.16.5, Forge 36.2.2, mod 2.0.0, Macaw's Paintings 1.0.2 and Infernal Expansion 1.3

**Comment by GeheimagentNr1** [comment]
Which mod added the modded paintings?

**Comment by faeldray** [comment]
I can't remember which painting I choose but I just did another test and I got the same crash with paintings from both [Infernal Expansion](https://www.curseforge.com/minecraft/mc-mods/infernal-expansion) and [Macaw's Paintings](https://www.curseforge.com/minecraft/mc-mods/macaws-paintings).

I did notice that if the painting size I had chosen also had vanilla paintings of the same size, a vanilla painting would be selected when I loaded the game. But if the painting size only had modded paintings, that would cause it to crash instead.

**Comment by faeldray** [comment]
I was able to get the same crash with a much smaller mod list to reduce the chances of some weird interaction. I discovered that if I just had one mod that adds paintings (ie. either Infernal Expansion or Macaw's Paintings), when I loaded the game for the second time, the selectable painting would revert to a vanilla painting without issue. But if I had more than one mod that adds paintings (ie. both Infernal Expansion and Macaw's Paintings), that's when I would get the crash.

Crash report: https://gist.github.com/faeldray/9d722c43ec1a83078502851348d576b0

**Comment by GeheimagentNr1** [comment]
I've implemented a fix. Please test, if this fix works for you.
I will release this, if I get a positive response.
[SelectablePainting-1.16.5-2.0.1.zip](https://github.com/GeheimagentNr1/SelectablePainting/files/6913003/SelectablePainting-1.16.5-2.0.1.zip)

**Comment by faeldray** [comment]
Sorry it took me so long to test this. I just did though and no more crashes!

**Comment by GeheimagentNr1** [comment]
Fixed with version 2.0.1
