### ISSUE TITLE
Paintings move by themselves

### ISSUE THREAD

**Issue by cosmoderp** [GeheimagentNr1/SelectablePainting#4]
**Versions**
Minecraft Version: 1.19.2
Minecraft Forge Version: 43.2.8
Mod Version: 1.19.2-2.0.2

**Describe the bug**
I placed a selectable painting and it moves its position.  I timed it 3 times and each time it took about a minute to move (always to the same position).  I also created an instance with just this mod installed to rule out compatibility issues.  Also, save and quit, then reopening the game restores position, but 1 approximately 1 min later it moves again.  It seems it always move up 1 block and to the right 1 block but more testing could be done.

**To Reproduce**
1. Place painting of any size
2. Wait approximately 1 minute
3. Painting moves

**Expected behavior**
painting should remain in the position it is placed.

**Screenshots**
a GIF of it occurring
https://cdn.discordapp.com/attachments/927095519682125954/1107699713253310515/renderingIssue.gif

**Comment by GeheimagentNr1** [comment]
<table><tbody><tr><th>Status:</th><td>Fixed</td></tr><tr><th>Issue type:</th><td>Bug</td></tr><tr><th>Fix type:</th><td>Bugfix</td></tr><tr><th>Fix version:</th><td>2.0.3</td></tr><tr><th>Fix release date:</th><td>31.05.23</td></tr></tbody></table>

**Issue confirmed for:**

* Minecraft version: 1.19.2  
   Minecraft Forge Version: 43.2.8   
   Mod version: 2.0.2  
* Minecraft Version: 1.19.2  
   Minecraft Forge Version: 43.2.8  
   Mod Version: 2.0.2

It was tested with Painting Sizes 1x1 and 2x2. The issue could only be reproduced for 2x2, not for 1x1.

**TODOs:**

*   [x] Check with:  
    Minecraft Version: 1.18.2  
    Minecraft Forge Version: 40.2.7  
    Mod Version: 2.0.1
*   [x] Check with:  
    Minecraft Version: 1.19.2  
    Minecraft Forge Version: 43.2.8  
    Mod Version: 2.0.2
*   [x] Check with:  
    Minecraft Version: 1.19.4  
    Minecraft Forge Version: 45.0.66  
    Mod Version: 2.0.2

**Comment by GeheimagentNr1** [comment]
The issue is fixed for 1.19.2 and 1.19.4 with version 2.0.3.
